controllers/AmbassadorController.php
<?php
namespace app_masukptn\controllers;

use Yii;
use app_tryout\models\Peserta;
use app_tryout\models\PesertaTambahan;
use app_tryout\models\Periode;
use app_tryout\models\PeriodeJenis;
use app_tryout\models\PeriodeKota;
use app_tryout\models\Sumber;
use app_tryout\models\Jurusan;
use technosmart\yii\web\Controller;

class AmbassadorController extends Controller
{
    /*public static $permissions = [
        'create'
    ];

    public function behaviors()
    {
        return [
            'access' => $this->access([
                [['index', 'view', 'create'], 'create'],
            ]),
        ];
    }*/

    protected function findModelPesertaByKodeEmail($kode, $email, $post = null)
    {
        if (($model['peserta'] = Peserta::find()->where(['kode' => $kode, 'email' => $email, 'status_aktif' => 'Aktif', 'status_duta' => 'Sudah Aktif'])->one()) !== null) {
            if ($post) {
                $model['peserta']->load($post);
            }
            return $model['peserta'];
        } else if (($model['peserta'] = PesertaTambahan::find()->where(['kode' => $kode, 'email' => $email])->one()) !== null && $model['peserta']->peserta->status_aktif == 'Aktif' && $model['peserta']->peserta->status_duta == 'Sudah Aktif') {
            $model['peserta'] = $model['peserta']->peserta;
            if ($post) {
                unset($post['Peserta']['kode']);
                unset($post['Peserta']['email']);
                $model['peserta']->load($post);
            }
            return $model['peserta'];
        } else {
            $model['peserta'] = new Peserta();
            $model['peserta']->kode = $kode;
            $model['peserta']->email = $email;
            $model['peserta']->validate(['kode', 'email']);
            if (!$model['peserta']->hasErrors()) {
                if ((Peserta::find()->where(['kode' => $kode, 'email' => $email])->one()) !== null ||
                    (PesertaTambahan::find()->join('INNER JOIN', 'peserta p', 'p.id = peserta_tambahan.id_peserta')->where(['peserta_tambahan.kode' => $kode, 'peserta_tambahan.email' => $email])->one()) !== null
                ) {
                    $model['peserta']->addErrors([
                        'kode' => 'Kamu belum terdaftar sebagai Ambassador. Silahkan klik tombol "Aktifkan" ambassador di halaman login pesertamu.',
                    ]);
                } else {
                    $notFound = false;
                    if ((Peserta::find()->where(['kode' => $kode])->one()) == null && (PesertaTambahan::find()->where(['kode' => $kode])->one()) == null) {
                        $model['peserta']->addErrors([
                            'kode' => 'Kode ambassador tidak ditemukan di periode sekarang yang sedang aktif',
                        ]);
                        $notFound = true;
                    }
                    if ((Peserta::find()->where(['email' => $email])->one()) == null && (PesertaTambahan::find()->where(['email' => $email])->one()) == null) {
                        $model['peserta']->addErrors([
                            'email' => 'Email ambassador tidak ditemukan di periode sekarang yang sedang aktif',
                        ]);
                        $notFound = true;
                    }
                    if (!$notFound) {
                        $model['peserta']->addErrors([
                            'kode' => 'Kombinasi kode dan email tidak ditemukan',
                            'email' => 'Kombinasi email dan kode tidak ditemukan',
                        ]);
                    }
                }
            }
            if ($post) {
                $model['peserta']->load($post);
            }
            return $model['peserta'];
        }
    }

    protected function findModelPesertaByKodeEmailDownload($kode, $email)
    {
        if (($model['peserta'] = Peserta::find()->where(['kode' => $kode, 'email' => $email])->one()) !== null) {
            return $model['peserta'];
        } else if (($model['peserta'] = PesertaTambahan::find()->where(['kode' => $kode, 'email' => $email])->one()) !== null) {
            return $model['peserta'];
        } else {
            $model['peserta'] = new Peserta();
            $model['peserta']->addErrors([
                'kode' => 'Kombinasi kode dan email tidak ditemukan',
                'email' => 'Kombinasi email dan kode tidak ditemukan',
            ]);
            return $model['peserta'];
        }
    }

    protected function findModelPeserta($id)
    {
        if (($model = Peserta::find()->where(['id' => $id])->one()) !== null) {
            return $model;
        } else {
            throw new \yii\web\HttpException(404, 'Data peserta tidak ditemukan.');
        }
    }

    protected function findModelPesertaTambahan($id)
    {
        if (($model = PesertaTambahan::find()->where(['id' => $id])->one()) !== null) {
            return $model;
        } else {
            throw new \yii\web\HttpException(404, 'Data peserta tidak ditemukan.');
        }
    }

    protected function findModelPeriodeJenis($id)
    {
        if (($model = PeriodeJenis::find()->where(['id' => $id])->one()) !== null) {
            return $model;
        } else {
            throw new \yii\web\HttpException(404, 'Kode kota tidak ditemukan.');
        }
    }

    protected function findModelPeriodeJenisByPeriode($id)
    {
        if (($model = PeriodeJenis::find()->where(['id_periode' => $id])->all()) !== null) {
            return $model;
        } else {
            throw new \yii\web\HttpException(404, 'Kode kota tidak ditemukan.');
        }
    }

    protected function findModelPeriodeKota($id)
    {
        if (($model = PeriodeKota::find()->where(['id' => $id])->one()) !== null) {
            return $model;
        } else {
            throw new \yii\web\HttpException(404, 'Kode kota tidak ditemukan.');
        }
    }

    public function actionIndex($kode = null, $email = null)
    {
        $error = true;

        $model['duta'] = new Peserta();
        $periode = Periode::getPeriodeAktif();
        
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();

            $model['duta'] = $this->findModelPesertaByKodeEmail($post['Peserta']['kode'], $post['Peserta']['email']);

            $error = false;
        } else {
            if ($kode || $email) {
                $model['duta'] = $this->findModelPesertaByKodeEmail($kode, $email);

                if (!$model['duta']->isNewRecord) {
                    Yii::$app->params['logoutAmbassador'] = true;
                    Yii::$app->params['kodeAmbassador'] = $kode;
                    Yii::$app->params['emailAmbassador'] = $email;
                }

                if ($model['duta']->hasErrors()) {
                    if (array_key_exists('kode', $model['duta']->errors) && $model['duta']->errors['kode'][0] == 'Kamu belum terdaftar sebagai Ambassador. Silahkan klik tombol "Aktifkan" ambassador di halaman login pesertamu.')
                        Yii::$app->session->setFlash('error', 'Kamu belum terdaftar sebagai Ambassador.<br><br>Silahkan klik tombol \"Aktifkan\" ambassador di halaman <a href=\"' . Yii::$app->urlManager->createUrl('peserta/login') . '\">login</a> pesertamu.');
                    else
                        Yii::$app->session->setFlash('error', 'Data ambassador tidak ditemukan.');
                }
            } else {
                $newSearch = true;
            }
        }

        if ($error)
            return $this->render('form-duta', [
                'model' => $model,
                'idPeriode' => $periode->id,
                'newSearch' => isset($newSearch) ? $newSearch : false,
                'title' => 'Dashboard Ambassador',
            ]);
        else
            return $this->redirect(['index', 'kode' => $model['duta']->kode, 'email' => $model['duta']->email]);
    }

    public function actionPendaftaran($kode, $email)
    {
        $error = true;

        $model['duta'] = $this->findModelPesertaByKodeEmail($kode, $email);
        if ($model['duta']->hasErrors()) {
            if (array_key_exists('kode', $model['duta']->errors) && $model['duta']->errors['kode'][0] == 'Kamu belum terdaftar sebagai Ambassador. Silahkan klik tombol "Aktifkan" ambassador di halaman login pesertamu.')
                throw new \yii\web\HttpException(404, 'Kamu belum terdaftar sebagai Ambassador. Silahkan klik tombol "Aktifkan" ambassador di halaman login pesertamu.');
            else
                throw new \yii\web\HttpException(404, 'Data ambassador tidak ditemukan.');
        }
        Yii::$app->params['logoutAmbassador'] = true;
        Yii::$app->params['kodeAmbassador'] = $kode;
        Yii::$app->params['emailAmbassador'] = $email;
        $model['peserta'] = new Peserta();
        $periode = Periode::getPeriodeAktif();
        $model['periode_jenis'] = $this->findModelPeriodeJenisByPeriode($periode->id);

        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();

            $model['peserta']->load($post);
            if (isset($post['PesertaTambahan'])) {
                foreach ($post['PesertaTambahan'] as $key => $value) {
                    if ($value['id'] > 0) {
                        $pesertaTambahan = $this->findModelPesertaTambahan($value['id']);
                        $pesertaTambahan->setAttributes($value);
                    } else if($value['id'] < 0) {
                        $pesertaTambahan = $this->findModelPesertaTambahan(($value['id']*-1));
                        $pesertaTambahan->isDeleted = true;
                    } else {
                        $pesertaTambahan = new PesertaTambahan();
                        $pesertaTambahan->setAttributes($value);
                    }
                    $model['peserta_tambahan'][] = $pesertaTambahan;
                }
            }

            $transaction = Peserta::getDb()->beginTransaction();

            try {

views/referral/form-dashboard.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

if (isset($title)) $this->title = $title;
if (isset($subtitle)) $this->subtitle = $subtitle;
if (isset($breadcrumbs)) $this->params['breadcrumbs'] = $breadcrumbs;

$jumlahTiket = 0;

foreach ($model['referral_agent']->transaksis as $key => $transaksi) {
    if ($transaksi->status_bayar == 'Sudah Bayar' && $transaksi->status_aktif == 'Aktif') {
        foreach ($transaksi->pesertas as $key => $peserta) {
            $jumlahTiket++;
        }
    }
}
?>
<style type="text/css">
.form-text:focus,
.form-textarea:focus,
.form-dropdown:focus {
  -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px rgba(102, 175, 233, .6);
          box-shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px rgba(102, 175, 233, .6);
}
</style>

<div class="has-bg-img padding-y-5">

<div class="margin-top-100"></div>

<h1 class="text-center fs-50 m-fs-30 text-orange fw-bold text-wrap text-uppercase" style="color: #FF7708;"><?= $title; ?></h1>

<div class="container padding-y-30">
    <div class="padding-30 shadow border-azure bg-lightest rounded-sm" style="max-width: 900px; width: 100%; margin-left: auto; margin-right: auto;">

    <div class="fs-16 m-fs-13 margin-x-30 m-margin-x-15 text-gray text-center">
        <hr class="border-azure border-top margin-y-0 margin-x-15 inline-block text-middle hidden-sm-less" style="width: 20px;">
        <span class="bg-lightest rounded-md border-light-azure padding-x-20 padding-y-10 inline-block">Akses Khusus Referral</span>
        <hr class="border-azure border-top margin-y-0 margin-x-15 inline-block text-middle hidden-sm-less" style="width: 20px;">
    </div>

    <div class="margin-top-30"></div>

    <div class="box box-gutter box-break-sm">
        <div class="box-12">
            <div class="box box-break-sm margin-bottom-10">
                <div class="box-2 padding-x-0 text-left text-gray">Nama :</div>
                <div class="box-10 m-padding-x-0 text-dark"><?= $model['referral_agent']->nama ?></div>
            </div>
            <div class="box box-break-sm margin-bottom-10">
                <div class="box-2 padding-x-0 text-left text-gray">Kode :</div>
                <div class="box-10 m-padding-x-0 text-dark"><?= $model['referral_agent']->kode ?></div>
            </div>
            <div class="box box-break-sm margin-bottom-10">
                <div class="box-2 padding-x-0 text-left text-gray">Handphone :</div>
                <div class="box-10 m-padding-x-0 text-dark"><?= $model['referral_agent']->handphone ?></div>
            </div>
            <div class="box box-break-sm margin-bottom-10">
                <div class="box-2 padding-x-0 text-left text-gray">Program :</div>
                <div class="box-10 m-padding-x-0 text-dark"><?= $model['referral_agent']->program ?></div>
            </div>
            <div class="box box-break-sm margin-bottom-10">
                <div class="box-2 padding-x-0 text-left text-gray">Sekolah :</div>
                <div class="box-10 m-padding-x-0 text-dark"><?= $model['referral_agent']->sekolah ?></div>
            </div>
            <div class="box box-break-sm margin-bottom-10">
                <div class="box-2 padding-x-0 text-left text-gray">Kota :</div>
                <div class="box-10 m-padding-x-0 text-dark"><?= $model['referral_agent']->regencies ? $model['referral_agent']->regencies->name : '(kosong)' ?></div>
            </div>
            <div class="box box-break-sm margin-bottom-10">
                <div class="box-2 padding-x-0 text-left text-gray">Provinsi :</div>
                <div class="box-10 m-padding-x-0 text-dark"><?= $model['referral_agent']->regencies ? $model['referral_agent']->regencies->province->name : '(kosong)' ?></div>
            </div>
            <div class="box box-break-sm margin-bottom-10">
                <div class="box-2 padding-x-0 text-left text-gray">Email :</div>
                <div class="box-10 m-padding-x-0 text-dark"><?= $model['referral_agent']->email ?></div>
            </div>
            <div class="box box-break-sm margin-bottom-10">
                <div class="box-2 padding-x-0 text-left text-gray">Nomor Identitas :</div>
                <div class="box-10 m-padding-x-0 text-dark"><?= $model['referral_agent']->nomor_identitas ?></div>
            </div>
            <div class="box box-break-sm margin-bottom-10">
                <div class="box-2 padding-x-0 text-left text-gray">Alamat Lengkap :</div>
                <div class="box-10 m-padding-x-0 text-dark"><?= $model['referral_agent']->alamat_lengkap ?></div>
            </div>
            <div class="box box-break-sm margin-bottom-10">
                <div class="box-2 padding-x-0 text-left text-gray">Catatan :</div>
                <div class="box-10 m-padding-x-0 text-dark"><span class="underline"><?= $model['referral_agent']->catatan ?></span></div>
            </div>
            <div class="box box-break-sm margin-bottom-10">
                <div class="box-2 padding-x-0 text-left text-gray">Total tiket :</div>
                <div class="box-10 m-padding-x-0 text-dark"><?= $jumlahTiket ?></div>
            </div>
            <div class="box box-break-sm margin-bottom-10">
                <div class="box-2 padding-x-0 text-left text-gray">Angka Hasil :</div>
                <div class="box-10 m-padding-x-0 text-dark">Rp <?= number_format((int)$jumlahTiket * (int)$model['referral_agent']->fee) ?></div>
            </div>
        </div>
    </div>

    <div class="margin-bottom-15"></div>

    <?php if ($model['referral_agent']->transaksis) : ?>        
    <div class="scroll-x">
    <table class="table margin-0">
        <thead>
            <tr>
                <th>Nama</th>
                <th>Kontak</th>
                <th>Jenis</th>
                <th>Lokasi</th>
                <th>Status</th>
                <th>E-Tiket</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($model['referral_agent']->transaksis as $key => $transaksi) : ?>
                <?php if (/*$transaksi->status_bayar == 'Sudah Bayar' && */$transaksi->status_aktif == 'Aktif') foreach ($transaksi->pesertas as $key => $peserta) : ?>
                    <tr>
                        <td>
                            <div class="fs-14 text-dark"><?= $peserta->nama ?></div>
                            <div>
                                <span class="text-gray">kode: </span>
                                <span class="text-dark"><?= $peserta->kode ?></span>
                            </div>
                        </td>
                        <td>
                            <div>
                                <i class="fa fa-envelope margin-right-5 text-gray" style="width: 10px;"></i>
                                <span class="text-dark"><?= $peserta->email ?></span>
                            </div>
                            <div>
                                <i class="fa fa-phone margin-right-5 text-gray" style="width: 10px;"></i>
                                <span class="text-dark"><?= $peserta->handphone ?></span>
                            </div>
                        </td>
                        <td>
                            <div class="fs-14 text-dark"><?= $peserta->id_periode_jenis ? $peserta->periodeJenis->nama : '(belum dipilih)' ?></div>
                            <div>
                                <span class="text-gray">Rp </span>
                                <span class="text-dark"><?= number_format($peserta->harga, 2) ?></span>
                            </div>
                        </td>
                        <td>
                            <div>
                                <i class="fa fa-map-marker margin-right-5 text-gray"></i>
                                <span class="text-dark"><?= $peserta->id_periode_kota ? $peserta->periodeKota->nama : '(belum dipilih)' ?></span>
                            </div>
                            <div>
                                <?= $peserta->id_periode_kota ? Html::a('Lihat Detail', ['detail-kota', 'id' => $peserta->id_periode_kota], ['modal-md' => '', 'modal-title' => 'Detail Lokasi']) : '' ?>
                            </div>
                        </td>
                        <?php
                            $color = 'red';
                            if ($transaksi->status_bayar == 'Dalam Proses Konfirmasi') $color = 'orange';
                            elseif ($transaksi->status_bayar == 'Sudah Bayar') $color = 'azure';
                        ?>
                        <td class="text-<?= $color ?>">
                            <i class="fa fa-circle margin-right-2"></i>
                            <?= $transaksi->status_bayar ?>
                        </td>
                        <td>
                            <?php if ($transaksi->status_bayar == 'Sudah Bayar') : ?>
                                <?= Html::a('Download', ['/peserta/download-kartu-ujian', 'kode' => $peserta->kode, 'email' => $peserta->email], ['class' => 'button button-sm border-azure text-azure']) ?>
                            <?php else : ?>
                                Belum tersedia
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </tbody>
    </table>
    </div>
    <?php endif; ?>

    <div class="margin-top-30"></div>

    <div class="clearfix">
        <?= Html::a('Tambah Peserta', ['pendaftaran'], ['class' => 'button button-md border-azure bg-azure button-block']) ?>
    </div>

    </div>
</div>

</div>

views/referral/form-login.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

if (isset($title)) $this->title = $title;
if (isset($subtitle)) $this->subtitle = $subtitle;
if (isset($breadcrumbs)) $this->params['breadcrumbs'] = $breadcrumbs;

//
$errorMessage = '';
$errorVue = false;
if ($model['login']->hasErrors()) {
    $errorMessage .= Html::errorSummary($model['login'], ['class' => '']);
}

/*if (isset($model['dev_child'])) foreach ($model['dev_child'] as $key => $devChild) {
    if ($devChild->hasErrors()) {
        $errorMessage .= Html::errorSummary($devChild, ['class' => '']);
        $errorVue = true; 
    }
}
if ($errorVue) {
    $this->registerJs(
        '$.each($("#app").data("yiiActiveForm").attributes, function() {
            this.status = 3;
        });
        $("#app").yiiActiveForm("validate");',
        5
    );
}*/
?>
<style type="text/css">
.form-text:focus,
.form-textarea:focus,
.form-dropdown:focus {
  -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px rgba(102, 175, 233, .6);
          box-shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px rgba(102, 175, 233, .6);
}
</style>

<div class="has-bg-img padding-y-5">

<div class="margin-top-100"></div>

<div class="container padding-y-30">
    <div class="padding-30 shadow border bg-lightest rounded-sm" style="max-width: 600px; width: 100%; margin-left: auto; margin-right: auto;">

    <h1 class="text-center fs-50 m-fs-30 text-orange fw-bold text-wrap text-uppercase" style="color: #FF7708;"><?= $title; ?></h1>

    <div class="margin-top-30"></div>

    <?php $form = ActiveForm::begin([/*'enableClientValidation' => true, */'options' => ['id' => 'app', 'enctype'=>'multipart/form-data']]); ?>
      
        <div class="box box-break-sm box-gutter box-equal">
            <div class="box-6">
                <?= $form->field($model['login'], 'kode', ['options' => ['class' => 'form-wrapper'], 'selectors' => ['error' => '.form-info']])->begin(); ?>
                    <?= Html::activeLabel($model['login'], 'kode', ['class' => 'form-label fw-bold text-uppercase text-gray', 'label' =>'Kode']); ?>
                    <?= Html::activeTextInput($model['login'], 'kode', ['class' => 'form-text rounded-xs', 'maxlength' => true]); ?>
                    <?= Html::error($model['login'], 'kode', ['class' => 'form-info']); ?>
                <?= $form->field($model['login'], 'kode')->end(); ?>
            </div>
            <div class="box-6">
                <?= $form->field($model['login'], 'handphone', ['options' => ['class' => 'form-wrapper'], 'selectors' => ['error' => '.form-info']])->begin(); ?>
                    <?= Html::activeLabel($model['login'], 'handphone', ['class' => 'form-label fw-bold text-uppercase text-gray', 'label' =>'Handphone']); ?>
                    <?= Html::activeTextInput($model['login'], 'handphone', ['class' => 'form-text rounded-xs', 'maxlength' => true]); ?>
                    <?= Html::error($model['login'], 'handphone', ['class' => 'form-info']); ?>
                <?= $form->field($model['login'], 'handphone')->end(); ?>
            </div>
        </div>

        <div class="margin-top-30"></div>
        
        <div class="form-wrapper clearfix">
            <?= Html::submitButton('Masuk/Login', ['class' => 'button button-lg button-block border-azure bg-azure hover-bg-lightest hover-text-azure']) ?>
        </div>
        
    <?php ActiveForm::end(); ?>

    </div>
</div>

<div class="margin-top-50"></div>

</div>

views/referral/syarat-ketentuan.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

if (isset($title)) $this->title = $title;
if (isset($subtitle)) $this->subtitle = $subtitle;
if (isset($breadcrumbs)) $this->params['breadcrumbs'] = $breadcrumbs;

?>
<?php if (!Yii::$app->request->isAjax) : ?>
<div class="has-bg-img padding-y-5">

<div class="margin-top-100"></div>

<h1 class="text-center fs-40 text-orange fw-bold text-wrap text-uppercase" style="color: #FF7708;"><?= $title; ?></h1>

<div class="container padding-y-30">
    <div class="padding-30 shadow border-azure bg-lightest rounded-sm" style="max-width: 600px; width: 100%; margin-left: auto; margin-right: auto;">
<?php endif; ?>

        <table class="table table-no-line">
            <tr>
                <td class="padding-x-0"><span class="bg-azure border-azure inline-block text-center" style="width:20px;height:20px;">1</span></td>
                <td class="padding-left-10">Ambassador adalah peserta yang telah mendaftarkan dirinya menjadi peserta MasukPTNid 2019 dan telah meng-klik tombol "Aktifkan Ambassador" pada halaman login peserta.</td>
            </tr>
            <tr>
                <td class="padding-x-0"><span class="bg-azure border-azure inline-block text-center" style="width:20px;height:20px;">2</span></td>
                <td class="padding-left-10">Ambassador bertugas untuk mempublikasikan kegiatan MasukPTNid - Tryout Nasional SBMPTN Test Center 2019 baik secara online maupun offline</td>
            </tr>
            <tr>
                <td class="padding-x-0"><span class="bg-azure border-azure inline-block text-center" style="width:20px;height:20px;">3</span></td>
                <td class="padding-left-10">Ambassador mempunyai keuntungan untuk mendapatkan hadiah-hadiah untuk setiap peserta yang mendaftarkan dirinya via link Ambassador dirinya sendiri.</td>
            </tr>
            <tr>
                <td class="padding-x-0"><span class="bg-azure border-azure inline-block text-center" style="width:20px;height:20px;">4</span></td>
                <td class="padding-left-10">Untuk mendapatkan hadiah-hadiah, tiap Ambassador dapat mendaftarkan peserta lainnya melalui link <a href="<?= Yii::$app->urlManager->createUrl(['ambassador/pendaftaran', 'kode' => $model['duta']->kode, 'email' => $model['duta']->email]) ?>">Ini</a>, atau klik tombol <a href="<?= Yii::$app->urlManager->createUrl(['ambassador/pendaftaran', 'kode' => $model['duta']->kode, 'email' => $model['duta']->email]) ?>">Tambah Poin</a> di halaman Ambassador masing-masing.</td>
            </tr>
            <tr>
                <td class="padding-x-0"><span class="bg-azure border-azure inline-block text-center" style="width:20px;height:20px;">5</span></td>
                <td class="padding-left-10 fw-bold">Peserta yang didaftarkan Ambassador hanya bisa untuk pembelian tiket 1 orang dalam 1 transaksi.</td>
            </tr>
            <tr>
                <td class="padding-x-0"><span class="bg-azure border-azure inline-block text-center" style="width:20px;height:20px;">6</span></td>
                <td class="padding-left-10 fw-bold">Peserta yang didaftarkan Ambassador tidak bisa untuk pembelian tiket 2 orang / lebih dalam 1 transaksi.</td>
            </tr>
            <tr>
                <td class="padding-x-0"><span class="bg-azure border-azure inline-block text-center" style="width:20px;height:20px;">7</span></td>
                <td class="padding-left-10 fw-bold">Tiap 1 peserta yang didaftarkan dan sudah melakukan pembayaran, Ambassador akan memperolah 15 Poin Ambassador yang bisa ditukarkan dengan hadiah - hadiah.</td>
            </tr>
            <tr>
                <td class="padding-x-0"><span class="bg-azure border-azure inline-block text-center" style="width:20px;height:20px;">8</span></td>
                <td class="padding-left-10">Hadiah - hadiah yang bisa ditukarkan dapat dilihat di link <a href="<?= Yii::$app->urlManager->createUrl(['ambassador/hadiah-ambassador', 'kode' => $model['duta']->kode, 'email' => $model['duta']->email]) ?>">ini</a>, atau klik tombol <a href="<?= Yii::$app->urlManager->createUrl(['ambassador/hadiah-ambassador', 'kode' => $model['duta']->kode, 'email' => $model['duta']->email]) ?>"></a>Hadiah Ambassador di halaman Ambassador masing-masing.</td>
            </tr>
            <tr>
                <td class="padding-x-0"><span class="bg-azure border-azure inline-block text-center" style="width:20px;height:20px;">9</span></td>
                <td class="padding-left-10">Waktu penukaran hadiah - hadiah akan diumumkan oleh panitia maksimal H-7 acara pada Instagram dan Official Account LINE @masukptnid.</td>
            </tr>
            <tr>
                <td class="padding-x-0"><span class="bg-azure border-azure inline-block text-center" style="width:20px;height:20px;">10</span></td>
                <td class="padding-left-10">Penerimaan hadiah - hadiah akan diberikan oleh panitia MAKSIMAL H+14 acara.</td>
            </tr>
            <tr>
                <td class="padding-x-0"><span class="bg-azure border-azure inline-block text-center" style="width:20px;height:20px;">11</span></td>
                <td class="padding-left-10">Ambassador dilarang keras mempublikasikan berita HOAX dan hal-hal yang mengandung SARA.</td>
            </tr>
            <tr>
                <td class="padding-x-0"><span class="bg-azure border-azure inline-block text-center" style="width:20px;height:20px;">12</span></td>
                <td class="padding-left-10">Ambassador dapat dengan bebas berkreasi dan melakukan improvisasi dalam mendapatkan peserta untuk mendaftar via Ambassador.<br>Contoh: Share postingan di Instagram masukptnid, story ajakan mendaftar via Ambassador, share timeline line @masukptnid, cetak poster acara secara offline, memasang poster acara di mading sekolah, mengajak anggota di grup kelas yang dimiliku untuk mendaftar, dan lain sebagainya.</td>
            </tr>
        </table>

<?php if (!Yii::$app->request->isAjax) : ?>
    </div>
</div>

<div class="margin-top-50"></div>

</div>
<?php endif; ?>